// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	"context"

	object_storage "github.com/piyushkumar96/generic-object-storage"

	ae "github.com/piyushkumar96/app-error"
	mock "github.com/stretchr/testify/mock"
)

// MockIStorageBackend is an autogenerated mock type for the IStorageBackend type
type MockIStorageBackend struct {
	mock.Mock
}

// CopyObject provides a mock function with given fields: ctx, srcPath, dstPath
func (_m *MockIStorageBackend) CopyObject(ctx context.Context, srcPath string, dstPath string) *ae.AppError {
	ret := _m.Called(ctx, srcPath, dstPath)

	if len(ret) == 0 {
		panic("no return value specified for CopyObject")
	}

	var r0 *ae.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *ae.AppError); ok {
		r0 = rf(ctx, srcPath, dstPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ae.AppError)
		}
	}

	return r0
}

// DeleteObject provides a mock function with given fields: ctx, path
func (_m *MockIStorageBackend) DeleteObject(ctx context.Context, path string) *ae.AppError {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 *ae.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string) *ae.AppError); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ae.AppError)
		}
	}

	return r0
}

// GetObject provides a mock function with given fields: ctx, path
func (_m *MockIStorageBackend) GetObject(ctx context.Context, path string) (object_storage.Object, *ae.AppError) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 object_storage.Object
	var r1 *ae.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string) (object_storage.Object, *ae.AppError)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) object_storage.Object); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Get(0).(object_storage.Object)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *ae.AppError); ok {
		r1 = rf(ctx, path)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ae.AppError)
		}
	}

	return r0, r1
}

// GetObjects provides a mock function with given fields: ctx, prefix
func (_m *MockIStorageBackend) GetObjects(ctx context.Context, prefix string) ([]object_storage.Object, *ae.AppError) {
	ret := _m.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for GetObjects")
	}

	var r0 []object_storage.Object
	var r1 *ae.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]object_storage.Object, *ae.AppError)); ok {
		return rf(ctx, prefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []object_storage.Object); ok {
		r0 = rf(ctx, prefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]object_storage.Object)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) *ae.AppError); ok {
		r1 = rf(ctx, prefix)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*ae.AppError)
		}
	}

	return r0, r1
}

// PutObject provides a mock function with given fields: ctx, path, content
func (_m *MockIStorageBackend) PutObject(ctx context.Context, path string, content []byte) *ae.AppError {
	ret := _m.Called(ctx, path, content)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *ae.AppError
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) *ae.AppError); ok {
		r0 = rf(ctx, path, content)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ae.AppError)
		}
	}

	return r0
}

// NewMockIStorageBackend creates a new instance of MockIStorageBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIStorageBackend(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIStorageBackend {
	mock := &MockIStorageBackend{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
