// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	context "context"

	storage "cloud.google.com/go/storage"
	mock "github.com/stretchr/testify/mock"
)

// MockIGCSClient is an autogenerated mock type for the IGCSClient type
type MockIGCSClient struct {
	mock.Mock
}

// Object provides a mock function with given fields: name
func (_m *MockIGCSClient) Object(name string) *storage.ObjectHandle {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Object")
	}

	var r0 *storage.ObjectHandle
	if rf, ok := ret.Get(0).(func(string) *storage.ObjectHandle); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ObjectHandle)
		}
	}

	return r0
}

// Objects provides a mock function with given fields: ctx, q
func (_m *MockIGCSClient) Objects(ctx context.Context, q *storage.Query) *storage.ObjectIterator {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Objects")
	}

	var r0 *storage.ObjectIterator
	if rf, ok := ret.Get(0).(func(context.Context, *storage.Query) *storage.ObjectIterator); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.ObjectIterator)
		}
	}

	return r0
}

// NewMockIGCSClient creates a new instance of MockIGCSClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIGCSClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIGCSClient {
	mock := &MockIGCSClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
